# Generated by Django 4.2.1 on 2023-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('coffee_shop', models.TextField()),
                ('coffee_beverage', models.CharField(max_length=300)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
