# Generated by Django 4.2.1 on 2025-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeedatabase',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
