# Generated by Django 4.2.1 on 2025-05-21 18:19

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0002_alter_coffeedatabase_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlavourNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour_notes', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeBeanDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roast_name', models.CharField(max_length=100)),
                ('coffee_roaster', models.CharField(max_length=100)),
                ('is_signle_origin', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('country_origin', models.ManyToManyField(related_name='countries', to='coffee_database.coffeeorigin')),
                ('country_roaster', models.ManyToManyField(related_name='roaster_country', to='coffee_database.coffeeorigin')),
                ('flavour_notes', models.ManyToManyField(related_name='flavours', to='coffee_database.flavournote')),
            ],
        ),
    ]
