# Generated by Django 4.2.1 on 2025-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0003_coffeeorigin_flavournote_coffeebeandatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebeandatabase',
            name='comment',
            field=models.CharField(default='', max_length=500),
        ),
    ]
