# Generated by Django 4.2.1 on 2025-05-21 19:15

from django.db import migrations


def add_countries(apps, schema_editor):
    Country = apps.get_model('coffee_database', 'CoffeeOrigin')
    print(Country)
    from django_countries import countries

    for code, name in countries:
        Country.objects.get_or_create(country=code)


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0004_coffeebeandatabase_comment'),
    ]

    operations = [
        migrations.RunPython(add_countries),
    ]
