# Generated by Django 4.2.1 on 2025-05-21 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0005_populates_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebeandatabase',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
