# Generated by Django 4.2.1 on 2025-05-22 11:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0006_coffeebeandatabase_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeebeandatabase',
            name='country_roaster',
        ),
        migrations.AddField(
            model_name='coffeebeandatabase',
            name='country_roaster',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
