# Generated by Django 4.2.1 on 2025-05-22 15:02

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0007_remove_coffeebeandatabase_country_roaster_and_more'),
    ]

    operations = [
    ]
