# Generated by Django 4.2.1 on 2025-05-22 15:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0008_country_database_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeorigin',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),

        
    ]
