# Generated by Django 4.2.1 on 2025-05-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0009_coffeeorigin_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffeeorigin',
            old_name='name',
            new_name='country_name',
        ),
    ]
