# Generated by Django 4.2.1 on 2025-05-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_database', '0011_add_country_names_to_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeebeandatabase',
            name='country_roaster',
            field=models.CharField(max_length=100),
        ),
    ]
